---
include:
  - board: nrfmicro@1.1.0/nrf52840/flipped_zmk
    # shield: challenger nice_view_adapter nice_view
    shield: challenger nice_view
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
